config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index]

  resources :blogs, except: [:index, :new, :edit, :show] do
    member do
      get :toggle_status
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:edit, :index, :show, :new, :show] do
    put :sort, on: :collection
  end

  get 'category/:id', to: 'categories#show', as: 'category_show'
  get 'palkafoodie/new', to: 'blogs#new'
  get 'palkafoodie', to: 'blogs#index'
  get 'palkafoodie/:id/edit', to: 'blogs#edit', as: 'edit_blog'
  get 'palkafoodie/:id', to: 'blogs#show', as: 'blog_show'
  get 'new', to: 'portfolios#new'
  get 'about-me', to: 'portfolios#about'
  get 'contact', to: 'portfolios#contact'
  get '/:id', to: 'portfolios#show', as: 'portfolio_show'
  get '/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'

  mount ActionCable.server => '/cable'

  root to: 'portfolios#index'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  mount_uploader :blog_image, BlogUploader

  validates_presence_of :title, :body, :subtitle, :category_id

  belongs_to :category, optional: true

  has_many :comments, dependent: :destroy

  def self.recent_blogs
  		order('created_at desc')
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  include WithBlogsConcern
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]
  access all: [:index, :show], site_admin: :all
  layout "blog"
  # GET /blogs
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.all.recent_blogs
    else
      @blogs = Blog.published.recent_blogs
    end
  end

  # GET /blogs/1
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new
      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to palkafoodie_path, notice: "You are not authorized to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to blog_show_path(@blog), notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to blog_show_path(@blog), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to palkafoodie_path, notice: 'Blog was successfully destroyed.'
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
      redirect_to palkafoodie_path, notice: 'Post status has been successfully updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def blog_params
      params.require(:blog).permit(:title, :body, :subtitle, :category_id, :status, :blog_image)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper

  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  def blog_status_color blog
    if blog.draft?
		'color: red;'
    elsif blog.published?
    'color: green;'
    end
	end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="breadcrumb blogcrumb">
    <div class="col">
      <%= link_to fa_icon('file-text'), toggle_status_blog_path(blog), style: blog_status_color(blog) if logged_in?(:site_admin) %>
      <%= link_to fa_icon('pencil-square-o'), edit_blog_path(blog) if logged_in?(:site_admin) %>
      <%= link_to fa_icon('trash'), blog, method: :delete, data: { confirm: 'Are you sure you want to delete this post' } if logged_in?(:site_admin) %>
      <%= blog.status %>
    </div>
  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>
      <div class="post-preview">
        <h2 class="post-title">
          <%= link_to blog.title, blog_show_path(blog) %>
          <h3 class="post-subtitle">
          <%= blog.subtitle %>
          </h3>
        </h2>
        <p class="post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago
      </div>
    </div>
  </div>
</div>
<hr>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, image: :error) %>
    <% end %>
  <% end %>



    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :category_id %>
      <%= form.collection_select(:category_id, Category.all, :id, :title,
                              {
                                include_blank: true
                              },
                              class: 'form-control'
                              )
      %>
    </div>

    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :body %>
      <%= form.text_area :body, class: 'form-control', rows: 15 %>
    </div>

    <div class="form-group">
      <label class="btn btn-primary">
        Upload image <%= form.file_field :blog_image, style: 'display:none;' %>
      </label>
    </div>

  <div class="form-group">
    <%= form.submit 'Save Blog Item', class: 'btn btn-primary btn-block' %>
  </div>


<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <%= render 'form', blog: @blog %>


</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main blog-index">
  <%= render @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <%= render 'form', blog: @blog %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">
  <% if logged_in?(:site_admin) %>
    <%= render partial: 'blogs/admin_actions', locals: { blog: @blog } %>
  <% end %>
  <h2 class="section-heading"><%= @blog.title %></h2>
  <h3 class="subheading"><%= @blog.subtitle %></h3>
    <p>
      <%= image_tag blog_img(@blog.blog_image).to_s, width: "100%" %>
    </p>
    <p>
      <%= @blog.body %>
    </p>

    <%= render 'comments/comment_form' %>

    <%= render @blog.comments %>

    <div id="comments" data-blog-id="<%= @blog.id %>">
    <%= render @blog.comments %>
  </div>
</div>