config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index]

  resources :blogs, except: [:index, :new, :edit, :show] do
    member do
      get :toggle_status
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:edit, :index, :show, :new, :show] do
    put :sort, on: :collection
  end

  get 'category/:id', to: 'categories#show', as: 'category_show'
  get 'palkafoodie/new', to: 'blogs#new'
  get 'palkafoodie', to: 'blogs#index'
  get 'palkafoodie/:id/edit', to: 'blogs#edit', as: 'edit_blog'
  get 'palkafoodie/:id', to: 'blogs#show', as: 'blog_show'
  get 'new', to: 'portfolios#new'
  get 'about-me', to: 'portfolios#about'
  get 'contact', to: 'portfolios#contact'
  get '/:id', to: 'portfolios#show', as: 'portfolio_show'
  get '/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'

  mount ActionCable.server => '/cable'

  root to: 'portfolios#index'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged


  mount_uploader :image, PortfolioUploader

  validates_presence_of :title, :subtitle



  def self.by_position
  	order('position ASC')
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  # layout 'portfolio'
  access all: [:show, :index, :about], user: {except: [:destroy, :new, :create, :update, :edit, :sort, :about, :contact]}, site_admin: :all

  # GET /portfolios
  # GET /portfolios.json
  def index
    @portfolios = Portfolio.page(params[:page] || 1).per(6).by_position
    render action: :index, layout: request.xhr? == nil
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render body: nil
  end
  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @page_title = @portfolio.title
  end

  # GET /portfolios/new
  def new
    @portfolio = Portfolio.new
  end

  # GET /portfolios/1/edit
  def edit
  end

  def palkafoodie
    @page_title = "Palkafoodie"
  end

  def contact
    @page_title = "Contact"
  end


  # POST /portfolios
  # POST /portfolios.json
  def create

    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to root_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /portfolios/1
  # PATCH/PUT /portfolios/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to root_path, notice: 'Portfolio was successfully updated.' }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy
    @portfolio.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Portfolio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_portfolio
      @portfolio = Portfolio.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :image,
                                        :quality,
                                        )
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio, local: true) do |form| %>
  <% if portfolio.errors.any? %>
    <% portfolio.errors.full_messages.each do |error| %>
      <%= js add_gritter(error, image: :error) %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload image <%= form.file_field :image, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="card">
        <%= image_tag portfolio_img(@portfolio.image.thumb).to_s, width: '100%' %>
      </div>
    </div>
  </div>

    <hr>

    <div class="form-group">
      <%= form.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4 drop">
  <div class="card mb-5 shadow-sm flash" data-id="<%= portfolio_item.id %>">
    <a href="<%= portfolio_item.image %>" data-lightbox="image-1">
      <%= image_tag portfolio_img(portfolio_item.image.thumb).to_s, width: '100%', height: '100%' %>
      <span><%= portfolio_item.title %></span>
    </a>
    <% if logged_in?(:site_admin) %>
    <%= link_to 'Delete',portfolio_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
    <%= link_to 'Edit',edit_portfolio_path(portfolio_item), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/portfolios/contact.html.erb
<h1>Contact me!</h1>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">

  <%= link_to 'Back', root_path %>

  <%= render 'form', portfolio: @portfolio %>

</div>

app/views/portfolios/index.html.erb
<div id="photos_container">
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pagination">
        <%= paginate @portfolios %>
      </div>

      <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
        <%= render partial: "portfolio_item", collection:  @portfolios %>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">

  <%= link_to 'Back', root_path %>

  <%= render 'form', portfolio: @portfolio %>

</div>

app/views/portfolios/palkafoodie.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">Palkafoodie</h1>
    <p class="lead blog-description">Delicious recipes for the everyday food enthusiast!</p>
    <span>

    </span>
    <span>

    </span>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-3 offset-sm-1 blog-sidebar">
      <div class="sidebar-module sidebar-module-inset">
        <h4>About</h4>
        <p>Filling in the about nav column.</p>
      </div>

      <div class="sidebar-module">
        <h5>Topics Quick Look</h5>
      </div>
      <div class="sidebar-module">
        <h4>Elsewhere</h4>
        <ol class="list-unstyled social-links">
          <li><a href="https://github.com/cpalka87"><%= fa_icon "github" %></a></li>
          <li><a href="https://www.instagram.com/palkaphoto/"><%= fa_icon "instagram" %></a></li>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @portfolio.title %>
</p>


<%= link_to 'Edit', edit_portfolio_path(@portfolio.slug) %> |
<%= link_to 'Back', root_path %>