config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index]

  resources :blogs, except: [:index, :new, :edit, :show] do
    member do
      get :toggle_status
    end
  end

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:edit, :index, :show, :new, :show] do
    put :sort, on: :collection
  end

  get 'category/:id', to: 'categories#show', as: 'category_show'
  get 'palkafoodie/new', to: 'blogs#new'
  get 'palkafoodie', to: 'blogs#index'
  get 'palkafoodie/:id/edit', to: 'blogs#edit', as: 'edit_blog'
  get 'palkafoodie/:id', to: 'blogs#show', as: 'blog_show'
  get 'new', to: 'portfolios#new'
  get 'about-me', to: 'portfolios#about'
  get 'contact', to: 'portfolios#contact'
  get '/:id', to: 'portfolios#show', as: 'portfolio_show'
  get '/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'

  mount ActionCable.server => '/cable'

  root to: 'portfolios#index'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], image: :notice) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], image: :error) %>
<% else flash[:notice] %>
  <%= js add_gritter(flash[:notice], image: :notice) %>
<% end %>

app/views/shared/_application_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 pt-4 social-link">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Just an amateur developer whom heavily enjoys the culinary arts, and applying my creativity in both the forms of cuisine and photography.</p>
          <p class="text-muted">Check out my Github, Instagram, and sister site (PalkaFoodie) below!</p>

            <a href="https://github.com/cpalka87" class="social-link">
              <span style='margin-right: .3em; font-size: 1.5em;'><%= fa_icon "github" %></span>
            </a>
            <a href="https://www.instagram.com/palkaphoto/" class="social-link">
              <span style='font-size: 1.5em;'><%= fa_icon "instagram" %></span>
            </a>
            <a href="#" class="social-link">
              <span style='font-size: 1.5em;'><%= fa_icon('lemon', type: :solid) %></span>
            </a>

        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper 'text-white', 'Portfolio' %></li>
            <% if logged_in?(:site_admin) %>
            <li><%= link_to "New", new_path, class: 'text-white' %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between social-link width-style">
      <a href="http://www.palkaphoto.com/" class="navbar-brand d-flex align-items-center">
        <strong>PalkaPhoto</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

app/views/shared/_blog_masthead.html.erb
<header class="masthead">
  <div class="overlay">
    <figure>
      <div class="slide">
        <%= image_tag "foodbanner.jpg" %>
      </div>
      <div class="slide">
        <%= image_tag "foodbanner2.jpg" %>
      </div>
      <div class="slide">
        <%= image_tag "foodbanner.jpg" %>
      </div>
      <div class="slide">
        <%= image_tag "foodbanner2.jpg" %>
      </div>
      <div class="slide">
        <%= image_tag "foodbanner.jpg" %>
      </div>
    </figure>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
          <h1>PalkaFoodie</h1>
          <span class="subheading">Culinary creations & Recipes by yours truly</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="http://www.palkaphoto.com/">PalkaPhoto</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Home', palkafoodie_path, style: 'nav-link' %>
        </li>
        <% if current_user.is_a?(GuestUser) %>
          <li class="nav-item"><%= link_to "Register", new_user_registration_path %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <li class="nav-item"><%= link_to "My Account", edit_user_registration_path %></li>
        <% end %>
        <% if logged_in?(:site_admin) %>
          <li class="nav-item"><%= link_to "New", palkafoodie_new_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h3>Categories</h3>
    <% @side_bar_categories.each do |category| %>
      <p class='category-list'><%= link_to category.title, category_show_path(category) %></p>
    <% end %>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/cpalka87"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.instagram.com/palkaphoto/"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <!-- <a href="#">Back to top</a> -->
    </p>
    <p class="text-center"><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">

    <% if current_user.is_a?(GuestUser) %>
    <h1 class="jumbotron-heading">Welcome!</h1>
    <% else %>
    <h1 class="jumbotron-heading">Welcome <%= current_user.first_name %>!</h1>
    <% end %>
    <h3><%= source_helper %></h3>
    <span class="element lead jumbotron-text"></span>
    <p>
      <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a>
      <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
    </p>
  </div>
</section>